// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//协议编号
type PbNum int32

const (
	PbNum_Login            PbNum = 0
	PbNum_Say              PbNum = 1
	PbNum_SayStatusConfirm PbNum = 2
)

var PbNum_name = map[int32]string{
	0: "Login",
	1: "Say",
	2: "SayStatusConfirm",
}

var PbNum_value = map[string]int32{
	"Login":            0,
	"Say":              1,
	"SayStatusConfirm": 2,
}

func (x PbNum) String() string {
	return proto.EnumName(PbNum_name, int32(x))
}

func (PbNum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

//聊天消息状态
type ChatMessageStatus int32

const (
	ChatMessageStatus_Reached ChatMessageStatus = 0
	ChatMessageStatus_Looked  ChatMessageStatus = 1
)

var ChatMessageStatus_name = map[int32]string{
	0: "Reached",
	1: "Looked",
}

var ChatMessageStatus_value = map[string]int32{
	"Reached": 0,
	"Looked":  1,
}

func (x ChatMessageStatus) String() string {
	return proto.EnumName(ChatMessageStatus_name, int32(x))
}

func (ChatMessageStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

//请求状态
type RequestStatus int32

const (
	RequestStatus_SUCCESS RequestStatus = 0
	RequestStatus_FAIL    RequestStatus = 1
)

var RequestStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
}

var RequestStatus_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
}

func (x RequestStatus) String() string {
	return proto.EnumName(RequestStatus_name, int32(x))
}

func (RequestStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

type C_Request struct {
	PbNum                PbNum    `protobuf:"varint,1,opt,name=PbNum,proto3,enum=pb.PbNum" json:"PbNum,omitempty"`
	Object               *any.Any `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C_Request) Reset()         { *m = C_Request{} }
func (m *C_Request) String() string { return proto.CompactTextString(m) }
func (*C_Request) ProtoMessage()    {}
func (*C_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *C_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C_Request.Unmarshal(m, b)
}
func (m *C_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C_Request.Marshal(b, m, deterministic)
}
func (m *C_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C_Request.Merge(m, src)
}
func (m *C_Request) XXX_Size() int {
	return xxx_messageInfo_C_Request.Size(m)
}
func (m *C_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_C_Request.DiscardUnknown(m)
}

var xxx_messageInfo_C_Request proto.InternalMessageInfo

func (m *C_Request) GetPbNum() PbNum {
	if m != nil {
		return m.PbNum
	}
	return PbNum_Login
}

func (m *C_Request) GetObject() *any.Any {
	if m != nil {
		return m.Object
	}
	return nil
}

//登陆请求
type C_LoginRequest struct {
	AccountID            string   `protobuf:"bytes,1,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C_LoginRequest) Reset()         { *m = C_LoginRequest{} }
func (m *C_LoginRequest) String() string { return proto.CompactTextString(m) }
func (*C_LoginRequest) ProtoMessage()    {}
func (*C_LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *C_LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C_LoginRequest.Unmarshal(m, b)
}
func (m *C_LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C_LoginRequest.Marshal(b, m, deterministic)
}
func (m *C_LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C_LoginRequest.Merge(m, src)
}
func (m *C_LoginRequest) XXX_Size() int {
	return xxx_messageInfo_C_LoginRequest.Size(m)
}
func (m *C_LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_C_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_C_LoginRequest proto.InternalMessageInfo

func (m *C_LoginRequest) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *C_LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

//登陆应答
type S_LoginResponse struct {
	RequestStatus        RequestStatus `protobuf:"varint,1,opt,name=RequestStatus,proto3,enum=pb.RequestStatus" json:"RequestStatus,omitempty"`
	UID                  string        `protobuf:"bytes,2,opt,name=UID,proto3" json:"UID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *S_LoginResponse) Reset()         { *m = S_LoginResponse{} }
func (m *S_LoginResponse) String() string { return proto.CompactTextString(m) }
func (*S_LoginResponse) ProtoMessage()    {}
func (*S_LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *S_LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S_LoginResponse.Unmarshal(m, b)
}
func (m *S_LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S_LoginResponse.Marshal(b, m, deterministic)
}
func (m *S_LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S_LoginResponse.Merge(m, src)
}
func (m *S_LoginResponse) XXX_Size() int {
	return xxx_messageInfo_S_LoginResponse.Size(m)
}
func (m *S_LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_S_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_S_LoginResponse proto.InternalMessageInfo

func (m *S_LoginResponse) GetRequestStatus() RequestStatus {
	if m != nil {
		return m.RequestStatus
	}
	return RequestStatus_SUCCESS
}

func (m *S_LoginResponse) GetUID() string {
	if m != nil {
		return m.UID
	}
	return ""
}

//私聊
type C_ChatToSomeOneRequest struct {
	TargetUID            string   `protobuf:"bytes,1,opt,name=TargetUID,proto3" json:"TargetUID,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C_ChatToSomeOneRequest) Reset()         { *m = C_ChatToSomeOneRequest{} }
func (m *C_ChatToSomeOneRequest) String() string { return proto.CompactTextString(m) }
func (*C_ChatToSomeOneRequest) ProtoMessage()    {}
func (*C_ChatToSomeOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}

func (m *C_ChatToSomeOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C_ChatToSomeOneRequest.Unmarshal(m, b)
}
func (m *C_ChatToSomeOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C_ChatToSomeOneRequest.Marshal(b, m, deterministic)
}
func (m *C_ChatToSomeOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C_ChatToSomeOneRequest.Merge(m, src)
}
func (m *C_ChatToSomeOneRequest) XXX_Size() int {
	return xxx_messageInfo_C_ChatToSomeOneRequest.Size(m)
}
func (m *C_ChatToSomeOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_C_ChatToSomeOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_C_ChatToSomeOneRequest proto.InternalMessageInfo

func (m *C_ChatToSomeOneRequest) GetTargetUID() string {
	if m != nil {
		return m.TargetUID
	}
	return ""
}

func (m *C_ChatToSomeOneRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

//私聊应答
type S_ChatToSomeOneResponse struct {
	RequestStatus        RequestStatus     `protobuf:"varint,1,opt,name=RequestStatus,proto3,enum=pb.RequestStatus" json:"RequestStatus,omitempty"`
	ChatMessageStatus    ChatMessageStatus `protobuf:"varint,2,opt,name=ChatMessageStatus,proto3,enum=pb.ChatMessageStatus" json:"ChatMessageStatus,omitempty"`
	TargetUID            string            `protobuf:"bytes,3,opt,name=TargetUID,proto3" json:"TargetUID,omitempty"`
	MessageID            int64             `protobuf:"varint,4,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *S_ChatToSomeOneResponse) Reset()         { *m = S_ChatToSomeOneResponse{} }
func (m *S_ChatToSomeOneResponse) String() string { return proto.CompactTextString(m) }
func (*S_ChatToSomeOneResponse) ProtoMessage()    {}
func (*S_ChatToSomeOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{4}
}

func (m *S_ChatToSomeOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S_ChatToSomeOneResponse.Unmarshal(m, b)
}
func (m *S_ChatToSomeOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S_ChatToSomeOneResponse.Marshal(b, m, deterministic)
}
func (m *S_ChatToSomeOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S_ChatToSomeOneResponse.Merge(m, src)
}
func (m *S_ChatToSomeOneResponse) XXX_Size() int {
	return xxx_messageInfo_S_ChatToSomeOneResponse.Size(m)
}
func (m *S_ChatToSomeOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_S_ChatToSomeOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_S_ChatToSomeOneResponse proto.InternalMessageInfo

func (m *S_ChatToSomeOneResponse) GetRequestStatus() RequestStatus {
	if m != nil {
		return m.RequestStatus
	}
	return RequestStatus_SUCCESS
}

func (m *S_ChatToSomeOneResponse) GetChatMessageStatus() ChatMessageStatus {
	if m != nil {
		return m.ChatMessageStatus
	}
	return ChatMessageStatus_Reached
}

func (m *S_ChatToSomeOneResponse) GetTargetUID() string {
	if m != nil {
		return m.TargetUID
	}
	return ""
}

func (m *S_ChatToSomeOneResponse) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

//客户端确认收到私聊消息
type C_SomeOneConfirmMessageRequest struct {
	ChatMessageStatus    ChatMessageStatus `protobuf:"varint,1,opt,name=ChatMessageStatus,proto3,enum=pb.ChatMessageStatus" json:"ChatMessageStatus,omitempty"`
	TargetUID            string            `protobuf:"bytes,2,opt,name=TargetUID,proto3" json:"TargetUID,omitempty"`
	MessageID            int64             `protobuf:"varint,3,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *C_SomeOneConfirmMessageRequest) Reset()         { *m = C_SomeOneConfirmMessageRequest{} }
func (m *C_SomeOneConfirmMessageRequest) String() string { return proto.CompactTextString(m) }
func (*C_SomeOneConfirmMessageRequest) ProtoMessage()    {}
func (*C_SomeOneConfirmMessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{5}
}

func (m *C_SomeOneConfirmMessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C_SomeOneConfirmMessageRequest.Unmarshal(m, b)
}
func (m *C_SomeOneConfirmMessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C_SomeOneConfirmMessageRequest.Marshal(b, m, deterministic)
}
func (m *C_SomeOneConfirmMessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C_SomeOneConfirmMessageRequest.Merge(m, src)
}
func (m *C_SomeOneConfirmMessageRequest) XXX_Size() int {
	return xxx_messageInfo_C_SomeOneConfirmMessageRequest.Size(m)
}
func (m *C_SomeOneConfirmMessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_C_SomeOneConfirmMessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_C_SomeOneConfirmMessageRequest proto.InternalMessageInfo

func (m *C_SomeOneConfirmMessageRequest) GetChatMessageStatus() ChatMessageStatus {
	if m != nil {
		return m.ChatMessageStatus
	}
	return ChatMessageStatus_Reached
}

func (m *C_SomeOneConfirmMessageRequest) GetTargetUID() string {
	if m != nil {
		return m.TargetUID
	}
	return ""
}

func (m *C_SomeOneConfirmMessageRequest) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

//服务端通知私聊消息给某人
type S_SomeOneReviceMessageResponse struct {
	SenderUID            string   `protobuf:"bytes,1,opt,name=SenderUID,proto3" json:"SenderUID,omitempty"`
	MessageID            int64    `protobuf:"varint,2,opt,name=MessageID,proto3" json:"MessageID,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=Message,proto3" json:"Message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *S_SomeOneReviceMessageResponse) Reset()         { *m = S_SomeOneReviceMessageResponse{} }
func (m *S_SomeOneReviceMessageResponse) String() string { return proto.CompactTextString(m) }
func (*S_SomeOneReviceMessageResponse) ProtoMessage()    {}
func (*S_SomeOneReviceMessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{6}
}

func (m *S_SomeOneReviceMessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_S_SomeOneReviceMessageResponse.Unmarshal(m, b)
}
func (m *S_SomeOneReviceMessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_S_SomeOneReviceMessageResponse.Marshal(b, m, deterministic)
}
func (m *S_SomeOneReviceMessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_S_SomeOneReviceMessageResponse.Merge(m, src)
}
func (m *S_SomeOneReviceMessageResponse) XXX_Size() int {
	return xxx_messageInfo_S_SomeOneReviceMessageResponse.Size(m)
}
func (m *S_SomeOneReviceMessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_S_SomeOneReviceMessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_S_SomeOneReviceMessageResponse proto.InternalMessageInfo

func (m *S_SomeOneReviceMessageResponse) GetSenderUID() string {
	if m != nil {
		return m.SenderUID
	}
	return ""
}

func (m *S_SomeOneReviceMessageResponse) GetMessageID() int64 {
	if m != nil {
		return m.MessageID
	}
	return 0
}

func (m *S_SomeOneReviceMessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("pb.PbNum", PbNum_name, PbNum_value)
	proto.RegisterEnum("pb.ChatMessageStatus", ChatMessageStatus_name, ChatMessageStatus_value)
	proto.RegisterEnum("pb.RequestStatus", RequestStatus_name, RequestStatus_value)
	proto.RegisterType((*C_Request)(nil), "pb.C_Request")
	proto.RegisterType((*C_LoginRequest)(nil), "pb.C_LoginRequest")
	proto.RegisterType((*S_LoginResponse)(nil), "pb.S_LoginResponse")
	proto.RegisterType((*C_ChatToSomeOneRequest)(nil), "pb.C_ChatToSomeOneRequest")
	proto.RegisterType((*S_ChatToSomeOneResponse)(nil), "pb.S_ChatToSomeOneResponse")
	proto.RegisterType((*C_SomeOneConfirmMessageRequest)(nil), "pb.C_SomeOneConfirmMessageRequest")
	proto.RegisterType((*S_SomeOneReviceMessageResponse)(nil), "pb.S_SomeOneReviceMessageResponse")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x51, 0x6f, 0xd3, 0x30,
	0x10, 0x9e, 0x93, 0xad, 0x5d, 0x6e, 0x62, 0x64, 0xd6, 0x80, 0x32, 0x55, 0xa3, 0xca, 0x03, 0xaa,
	0xaa, 0x29, 0x13, 0xe3, 0x81, 0xe7, 0xca, 0x05, 0xa9, 0xa8, 0x40, 0x65, 0xaf, 0x2f, 0x08, 0x29,
	0x72, 0x52, 0x2f, 0x2b, 0xd0, 0xb8, 0xc4, 0xce, 0x50, 0x7f, 0x0e, 0xbf, 0x89, 0x3f, 0x84, 0x92,
	0x3a, 0x69, 0x93, 0x4d, 0xbc, 0xec, 0xcd, 0xfe, 0xee, 0xee, 0xbb, 0xef, 0xbe, 0xb3, 0x01, 0xb4,
	0x50, 0xda, 0x5f, 0xa5, 0x52, 0x4b, 0x6c, 0xad, 0xc2, 0xb3, 0x97, 0xb1, 0x94, 0xf1, 0x4f, 0x71,
	0x59, 0x20, 0x61, 0x76, 0x73, 0xc9, 0x93, 0xf5, 0x26, 0xec, 0x7d, 0x05, 0x87, 0x04, 0x54, 0xfc,
	0xca, 0x84, 0xd2, 0xf8, 0x15, 0x1c, 0x4c, 0xc3, 0xcf, 0xd9, 0xb2, 0x83, 0x7a, 0xa8, 0x7f, 0x7c,
	0xe5, 0xf8, 0xab, 0xd0, 0x2f, 0x00, 0xba, 0xc1, 0xf1, 0x05, 0xb4, 0x64, 0xf8, 0x5d, 0x44, 0xba,
	0x63, 0xf5, 0x50, 0xff, 0xe8, 0xea, 0xd4, 0xdf, 0x30, 0xfb, 0x25, 0xb3, 0x3f, 0x4c, 0xd6, 0xd4,
	0xe4, 0x78, 0x1f, 0xe1, 0x98, 0x04, 0x13, 0x19, 0x2f, 0x92, 0xb2, 0x41, 0x17, 0x9c, 0x61, 0x14,
	0xc9, 0x2c, 0xd1, 0xe3, 0x51, 0xd1, 0xc4, 0xa1, 0x5b, 0x00, 0x9f, 0xc1, 0xe1, 0x94, 0x2b, 0xf5,
	0x5b, 0xa6, 0xf3, 0x82, 0xdf, 0xa1, 0xd5, 0xdd, 0xfb, 0x06, 0x4f, 0x59, 0xc9, 0xa5, 0x56, 0x32,
	0x51, 0x02, 0xbf, 0x83, 0x27, 0x86, 0x97, 0x69, 0xae, 0x33, 0x65, 0x54, 0x9f, 0xe4, 0xaa, 0x6b,
	0x01, 0x5a, 0xcf, 0xc3, 0x2e, 0xd8, 0xb3, 0xf1, 0xc8, 0xb4, 0xc8, 0x8f, 0xde, 0x14, 0x9e, 0x93,
	0x80, 0xdc, 0x72, 0x7d, 0x2d, 0x99, 0x5c, 0x8a, 0x2f, 0x89, 0xd8, 0x51, 0x7c, 0xcd, 0xd3, 0x58,
	0xe8, 0xd9, 0x56, 0x71, 0x05, 0xe0, 0x0e, 0xb4, 0x3f, 0x09, 0xa5, 0x78, 0x2c, 0x0c, 0x5b, 0x79,
	0xf5, 0xfe, 0x22, 0x78, 0xc1, 0x9a, 0x94, 0x8f, 0x15, 0x4e, 0xe0, 0x24, 0x67, 0x34, 0x3d, 0x4c,
	0xb1, 0x55, 0x14, 0x3f, 0xcb, 0x8b, 0xef, 0x05, 0xe9, 0xfd, 0xfc, 0xfa, 0x44, 0x76, 0x73, 0xa2,
	0x2e, 0x38, 0x26, 0x7d, 0x3c, 0xea, 0xec, 0xf7, 0x50, 0xdf, 0xa6, 0x5b, 0xc0, 0xfb, 0x83, 0xe0,
	0x9c, 0x04, 0x66, 0x1e, 0x22, 0x93, 0x9b, 0x45, 0xba, 0x34, 0xd1, 0xd2, 0xb0, 0x07, 0x35, 0xa2,
	0xc7, 0x68, 0xb4, 0xfe, 0xab, 0xd1, 0x6e, 0x6a, 0xbc, 0x83, 0x73, 0x16, 0x54, 0x96, 0xdf, 0x2d,
	0x22, 0x51, 0x29, 0x34, 0xfe, 0x77, 0xc1, 0x61, 0x22, 0x99, 0x8b, 0x74, 0x67, 0xa7, 0x15, 0x50,
	0x67, 0xb7, 0x1a, 0xec, 0xbb, 0x1b, 0xb7, 0x6b, 0x1b, 0x1f, 0xbc, 0x31, 0x9f, 0x07, 0x3b, 0x70,
	0x50, 0x3c, 0x54, 0x77, 0x0f, 0xb7, 0xc1, 0x66, 0x7c, 0xed, 0x22, 0x7c, 0x0a, 0x2e, 0xe3, 0xeb,
	0xcd, 0x74, 0xc6, 0x37, 0xd7, 0x1a, 0x5c, 0x3c, 0xe0, 0x15, 0x3e, 0x82, 0x36, 0x15, 0x3c, 0xba,
	0x15, 0x73, 0x77, 0x0f, 0x03, 0xb4, 0x26, 0x52, 0xfe, 0x10, 0x73, 0x17, 0x0d, 0x5e, 0x37, 0x9e,
	0x4d, 0x9e, 0xc9, 0x66, 0x84, 0xbc, 0x67, 0xcc, 0xdd, 0xc3, 0x87, 0xb0, 0xff, 0x61, 0x38, 0x9e,
	0xb8, 0x28, 0x6c, 0x15, 0x9f, 0xf1, 0xed, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x3d, 0x4c,
	0x35, 0x06, 0x04, 0x00, 0x00,
}
